[2025-02-05T12:14:57.799+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T12:14:57.809+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.dim_vendedor_seed manual__2025-02-05T12:14:44+00:00 [queued]>
[2025-02-05T12:14:57.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.dim_vendedor_seed manual__2025-02-05T12:14:44+00:00 [queued]>
[2025-02-05T12:14:57.815+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T12:14:57.825+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtSeedLocalOperator): model_sales.dim_vendedor_seed> on 2025-02-05 12:14:44+00:00
[2025-02-05T12:14:57.829+0000] {standard_task_runner.py:63} INFO - Started process 2590 to run task
[2025-02-05T12:14:57.831+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_sales', 'model_sales.dim_vendedor_seed', 'manual__2025-02-05T12:14:44+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_sales.py', '--cfg-path', '/tmp/tmpm6zb9p2y']
[2025-02-05T12:14:57.833+0000] {standard_task_runner.py:91} INFO - Job 74: Subtask model_sales.dim_vendedor_seed
[2025-02-05T12:14:57.872+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_sales.model_sales.dim_vendedor_seed manual__2025-02-05T12:14:44+00:00 [running]> on host 98025f4a542d
[2025-02-05T12:14:57.932+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_sales' AIRFLOW_CTX_TASK_ID='model_sales.dim_vendedor_seed' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T12:14:44+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T12:14:44+00:00'
[2025-02-05T12:14:57.934+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T12:14:57.907+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T12:14:57.908+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmplrrxtj0d from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T12:14:57.914+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_sales__model_sales/target/partial_parse.msgpack
[2025-02-05T12:14:57.918+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T12:14:57.924+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T12:14:57.925+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf/profiles.yml.
[2025-02-05T12:14:57.926+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['seed', '--vars', '{"PROD_1": P005,                                 "PROD_2": P001,                                 "DATA_INICIO": 1999-01-01,                                 "DATA_FIM": 2025-02-05}', '--models', 'dim_vendedor', '--project-dir', '/tmp/tmplrrxtj0d', '--profiles-dir', '/tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf', '--profile', '***', '--target', 'prod']
 in /tmp/tmplrrxtj0d
[2025-02-05T12:14:57.938+0000] {logging_mixin.py:188} INFO - 12:14:57  Running with dbt=1.6.1
[2025-02-05T12:14:58.013+0000] {logging_mixin.py:188} INFO - 12:14:58  Registered adapter: postgres=1.6.1
[2025-02-05T12:14:58.027+0000] {logging_mixin.py:188} INFO - 12:14:58  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-02-05T12:14:58.029+0000] {logging_mixin.py:188} INFO - 12:14:58  Unable to do partial parsing because profile has changed
[2025-02-05T12:14:58.029+0000] {logging_mixin.py:188} INFO - 12:14:58  Unable to do partial parsing because env vars used in profiles.yml have changed
[2025-02-05T12:14:58.758+0000] {logging_mixin.py:188} INFO - 12:14:58  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T12:14:58.761+0000] {logging_mixin.py:188} INFO - 12:14:58
[2025-02-05T12:14:58.812+0000] {logging_mixin.py:188} INFO - 12:14:58  Concurrency: 1 threads (target='prod')
[2025-02-05T12:14:58.813+0000] {logging_mixin.py:188} INFO - 12:14:58
[2025-02-05T12:14:58.815+0000] {logging_mixin.py:188} INFO - 12:14:58  1 of 1 START seed file dm_sales.dim_vendedor ................................... [RUN]
[2025-02-05T12:14:58.878+0000] {logging_mixin.py:188} INFO - 12:14:58  1 of 1 OK loaded seed file dm_sales.dim_vendedor ............................... [INSERT 20 in 0.06s]
[2025-02-05T12:14:58.886+0000] {logging_mixin.py:188} INFO - 12:14:58
[2025-02-05T12:14:58.887+0000] {logging_mixin.py:188} INFO - 12:14:58  Finished running 1 seed in 0 hours 0 minutes and 0.12 seconds (0.12s).
[2025-02-05T12:14:58.893+0000] {logging_mixin.py:188} INFO - 12:14:58
[2025-02-05T12:14:58.894+0000] {logging_mixin.py:188} INFO - 12:14:58  Completed successfully
[2025-02-05T12:14:58.895+0000] {logging_mixin.py:188} INFO - 12:14:58
[2025-02-05T12:14:58.896+0000] {logging_mixin.py:188} INFO - 12:14:58  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T12:14:59.673+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T12:14:59.675+0000] {local.py:494} INFO - Inlets: []
[2025-02-05T12:14:59.675+0000] {local.py:495} INFO - Outlets: []
[2025-02-05T12:14:59.676+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T12:14:59.677+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T12:14:59.688+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_sales to None, run_after=None
[2025-02-05T12:14:59.707+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T12:14:59.715+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_sales, task_id=model_sales.dim_vendedor_seed, run_id=manual__2025-02-05T12:14:44+00:00, execution_date=20250205T121444, start_date=20250205T121457, end_date=20250205T121459
[2025-02-05T12:14:59.739+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T12:14:59.756+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T12:14:59.759+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
