[2025-02-05T13:30:03.976+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T13:30:03.996+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.dim_vendedor_seed manual__2025-02-05T13:29:45+00:00 [queued]>
[2025-02-05T13:30:04.009+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.dim_vendedor_seed manual__2025-02-05T13:29:45+00:00 [queued]>
[2025-02-05T13:30:04.010+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T13:30:04.027+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtSeedLocalOperator): model_sales.dim_vendedor_seed> on 2025-02-05 13:29:45+00:00
[2025-02-05T13:30:04.034+0000] {standard_task_runner.py:63} INFO - Started process 4099 to run task
[2025-02-05T13:30:04.037+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_sales', 'model_sales.dim_vendedor_seed', 'manual__2025-02-05T13:29:45+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_sales.py', '--cfg-path', '/tmp/tmpcdo9s_bz']
[2025-02-05T13:30:04.039+0000] {standard_task_runner.py:91} INFO - Job 119: Subtask model_sales.dim_vendedor_seed
[2025-02-05T13:30:04.111+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_sales.model_sales.dim_vendedor_seed manual__2025-02-05T13:29:45+00:00 [running]> on host 98025f4a542d
[2025-02-05T13:30:04.230+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_sales' AIRFLOW_CTX_TASK_ID='model_sales.dim_vendedor_seed' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T13:29:45+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T13:29:45+00:00'
[2025-02-05T13:30:04.233+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T13:30:07.201+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T13:30:07.203+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpwusmt7pk from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T13:30:07.210+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_sales__model_sales/target/partial_parse.msgpack
[2025-02-05T13:30:07.223+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T13:30:07.236+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T13:30:07.238+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf/profiles.yml.
[2025-02-05T13:30:07.239+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['seed', '--vars', '{"PROD": P003,                                 "LIMITE_QUANTIDADE": 500,                                 "DATA_INICIO": 1999-01-01,                                 "DATA_FIM": 2025-02-05}', '--models', 'dim_vendedor', '--project-dir', '/tmp/tmpwusmt7pk', '--profiles-dir', '/tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf', '--profile', '***', '--target', 'prod']
 in /tmp/tmpwusmt7pk
[2025-02-05T13:30:07.259+0000] {logging_mixin.py:188} INFO - 13:30:07  Running with dbt=1.6.1
[2025-02-05T13:30:07.417+0000] {logging_mixin.py:188} INFO - 13:30:07  Registered adapter: postgres=1.6.1
[2025-02-05T13:30:07.446+0000] {logging_mixin.py:188} INFO - 13:30:07  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-02-05T13:30:07.449+0000] {logging_mixin.py:188} INFO - 13:30:07  Unable to do partial parsing because profile has changed
[2025-02-05T13:30:07.451+0000] {logging_mixin.py:188} INFO - 13:30:07  Unable to do partial parsing because env vars used in profiles.yml have changed
[2025-02-05T13:30:09.281+0000] {logging_mixin.py:188} INFO - 13:30:09  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T13:30:09.288+0000] {logging_mixin.py:188} INFO - 13:30:09
[2025-02-05T13:30:09.434+0000] {logging_mixin.py:188} INFO - 13:30:09  Concurrency: 1 threads (target='prod')
[2025-02-05T13:30:09.436+0000] {logging_mixin.py:188} INFO - 13:30:09
[2025-02-05T13:30:09.443+0000] {logging_mixin.py:188} INFO - 13:30:09  1 of 1 START seed file dm_sales.dim_vendedor ................................... [RUN]
[2025-02-05T13:30:09.628+0000] {logging_mixin.py:188} INFO - 13:30:09  1 of 1 OK loaded seed file dm_sales.dim_vendedor ............................... [INSERT 20 in 0.18s]
[2025-02-05T13:30:09.654+0000] {logging_mixin.py:188} INFO - 13:30:09
[2025-02-05T13:30:09.655+0000] {logging_mixin.py:188} INFO - 13:30:09  Finished running 1 seed in 0 hours 0 minutes and 0.36 seconds (0.36s).
[2025-02-05T13:30:09.667+0000] {logging_mixin.py:188} INFO - 13:30:09
[2025-02-05T13:30:09.669+0000] {logging_mixin.py:188} INFO - 13:30:09  Completed successfully
[2025-02-05T13:30:09.671+0000] {logging_mixin.py:188} INFO - 13:30:09
[2025-02-05T13:30:09.673+0000] {logging_mixin.py:188} INFO - 13:30:09  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T13:30:10.491+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T13:30:10.494+0000] {local.py:494} INFO - Inlets: []
[2025-02-05T13:30:10.495+0000] {local.py:495} INFO - Outlets: []
[2025-02-05T13:30:10.496+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T13:30:10.496+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T13:30:10.513+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_sales to None, run_after=None
[2025-02-05T13:30:10.547+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T13:30:10.557+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_sales, task_id=model_sales.dim_vendedor_seed, run_id=manual__2025-02-05T13:29:45+00:00, execution_date=20250205T132945, start_date=20250205T133003, end_date=20250205T133010
[2025-02-05T13:30:10.598+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T13:30:10.622+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T13:30:10.626+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
