[2025-02-05T16:09:24.667+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T16:09:24.683+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.eventos_vendas_seed manual__2025-02-05T16:09:14+00:00 [queued]>
[2025-02-05T16:09:24.691+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.eventos_vendas_seed manual__2025-02-05T16:09:14+00:00 [queued]>
[2025-02-05T16:09:24.692+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T16:09:24.706+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtSeedLocalOperator): model_sales.eventos_vendas_seed> on 2025-02-05 16:09:14+00:00
[2025-02-05T16:09:24.710+0000] {standard_task_runner.py:63} INFO - Started process 740 to run task
[2025-02-05T16:09:24.713+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_sales', 'model_sales.eventos_vendas_seed', 'manual__2025-02-05T16:09:14+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_sales.py', '--cfg-path', '/tmp/tmplenyrxru']
[2025-02-05T16:09:24.716+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask model_sales.eventos_vendas_seed
[2025-02-05T16:09:24.768+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_sales.model_sales.eventos_vendas_seed manual__2025-02-05T16:09:14+00:00 [running]> on host 5c897c3a2254
[2025-02-05T16:09:24.845+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_sales' AIRFLOW_CTX_TASK_ID='model_sales.eventos_vendas_seed' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T16:09:14+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T16:09:14+00:00'
[2025-02-05T16:09:24.846+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T16:09:26.975+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T16:09:26.977+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpjaw6vytk from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T16:09:26.986+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_sales__model_sales/target/partial_parse.msgpack
[2025-02-05T16:09:26.993+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T16:09:27.004+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T16:09:27.006+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf/profiles.yml.
[2025-02-05T16:09:27.007+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['seed', '--vars', '{"PROD": "P003", "LIMITE_QUANTIDADE": "500", "DATA_INICIO": "1999-01-01", "DATA_FIM": "2025-02-05"}', '--models', 'eventos_vendas', '--project-dir', '/tmp/tmpjaw6vytk', '--profiles-dir', '/tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf', '--profile', '***', '--target', 'prod']
 in /tmp/tmpjaw6vytk
[2025-02-05T16:09:27.029+0000] {logging_mixin.py:188} INFO - 16:09:27  Running with dbt=1.6.1
[2025-02-05T16:09:27.139+0000] {logging_mixin.py:188} INFO - 16:09:27  Registered adapter: postgres=1.6.1
[2025-02-05T16:09:27.163+0000] {logging_mixin.py:188} INFO - 16:09:27  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-02-05T16:09:27.164+0000] {logging_mixin.py:188} INFO - 16:09:27  Unable to do partial parsing because profile has changed
[2025-02-05T16:09:27.166+0000] {logging_mixin.py:188} INFO - 16:09:27  Unable to do partial parsing because env vars used in profiles.yml have changed
[2025-02-05T16:09:28.557+0000] {logging_mixin.py:188} INFO - 16:09:28  Found 5 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T16:09:28.559+0000] {logging_mixin.py:188} INFO - 16:09:28
[2025-02-05T16:09:28.650+0000] {logging_mixin.py:188} INFO - 16:09:28  Concurrency: 1 threads (target='prod')
[2025-02-05T16:09:28.651+0000] {logging_mixin.py:188} INFO - 16:09:28
[2025-02-05T16:09:28.655+0000] {logging_mixin.py:188} INFO - 16:09:28  1 of 1 START seed file dm_sales.eventos_vendas ................................. [RUN]
[2025-02-05T16:09:29.376+0000] {logging_mixin.py:188} INFO - 16:09:29  1 of 1 OK loaded seed file dm_sales.eventos_vendas ............................. [INSERT 535 in 0.72s]
[2025-02-05T16:09:29.390+0000] {logging_mixin.py:188} INFO - 16:09:29
[2025-02-05T16:09:29.392+0000] {logging_mixin.py:188} INFO - 16:09:29  Finished running 1 seed in 0 hours 0 minutes and 0.83 seconds (0.83s).
[2025-02-05T16:09:29.402+0000] {logging_mixin.py:188} INFO - 16:09:29
[2025-02-05T16:09:29.403+0000] {logging_mixin.py:188} INFO - 16:09:29  Completed successfully
[2025-02-05T16:09:29.404+0000] {logging_mixin.py:188} INFO - 16:09:29
[2025-02-05T16:09:29.405+0000] {logging_mixin.py:188} INFO - 16:09:29  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T16:09:30.355+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T16:09:30.358+0000] {local.py:494} INFO - Inlets: []
[2025-02-05T16:09:30.358+0000] {local.py:495} INFO - Outlets: []
[2025-02-05T16:09:30.359+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T16:09:30.359+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T16:09:30.379+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_sales to 2025-02-05 04:00:00+00:00, run_after=2025-02-06 04:00:00+00:00
[2025-02-05T16:09:30.411+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T16:09:30.420+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_sales, task_id=model_sales.eventos_vendas_seed, run_id=manual__2025-02-05T16:09:14+00:00, execution_date=20250205T160914, start_date=20250205T160924, end_date=20250205T160930
[2025-02-05T16:09:30.444+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T16:09:30.464+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-05T16:09:30.466+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
