[2025-02-05T14:32:48.908+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T14:32:48.928+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.ad_hoc_rnk_amount_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T14:32:48.939+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.ad_hoc_rnk_amount_run manual__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-05T14:32:48.940+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-02-05T14:32:48.955+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.ad_hoc_rnk_amount_run> on 2025-02-04 00:00:00+00:00
[2025-02-05T14:32:48.960+0000] {standard_task_runner.py:63} INFO - Started process 322 to run task
[2025-02-05T14:32:48.964+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.ad_hoc_rnk_amount_run', 'manual__2025-02-04T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmp1fho7tm9']
[2025-02-05T14:32:48.966+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask model_credit_fraud.ad_hoc_rnk_amount_run
[2025-02-05T14:32:49.025+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.ad_hoc_rnk_amount_run manual__2025-02-04T00:00:00+00:00 [running]> on host eb17fa5f9c23
[2025-02-05T14:32:49.125+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.ad_hoc_rnk_amount_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T00:00:00+00:00'
[2025-02-05T14:32:49.128+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T14:32:52.136+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T14:32:52.137+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpf79ut46l from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T14:32:52.145+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-05T14:32:52.154+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T14:32:52.163+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T14:32:52.165+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-05T14:32:52.165+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'ad_hoc_rnk_amount', '--project-dir', '/tmp/tmpf79ut46l', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmpf79ut46l
[2025-02-05T14:32:52.186+0000] {logging_mixin.py:188} INFO - 14:32:52  Running with dbt=1.6.1
[2025-02-05T14:32:52.320+0000] {logging_mixin.py:188} INFO - 14:32:52  Registered adapter: postgres=1.6.1
[2025-02-05T14:32:53.008+0000] {logging_mixin.py:188} INFO - 14:32:53  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T14:32:53.011+0000] {logging_mixin.py:188} INFO - 14:32:53
[2025-02-05T14:32:53.087+0000] {logging_mixin.py:188} INFO - 14:32:53  Concurrency: 1 threads (target='prod')
[2025-02-05T14:32:53.089+0000] {logging_mixin.py:188} INFO - 14:32:53
[2025-02-05T14:32:53.094+0000] {logging_mixin.py:188} INFO - 14:32:53  1 of 1 START sql table model dm_credit_operations.ad_hoc_rnk_amount ............ [RUN]
[2025-02-05T14:33:04.730+0000] {logging_mixin.py:188} INFO - 14:33:04  1 of 1 OK created sql table model dm_credit_operations.ad_hoc_rnk_amount ....... [SELECT 3 in 11.63s]
[2025-02-05T14:33:04.744+0000] {logging_mixin.py:188} INFO - 14:33:04
[2025-02-05T14:33:04.746+0000] {logging_mixin.py:188} INFO - 14:33:04  Finished running 1 table model in 0 hours 0 minutes and 11.73 seconds (11.73s).
[2025-02-05T14:33:04.762+0000] {logging_mixin.py:188} INFO - 14:33:04
[2025-02-05T14:33:04.763+0000] {logging_mixin.py:188} INFO - 14:33:04  Completed successfully
[2025-02-05T14:33:04.764+0000] {logging_mixin.py:188} INFO - 14:33:04
[2025-02-05T14:33:04.764+0000] {logging_mixin.py:188} INFO - 14:33:04  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T14:33:05.556+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T14:33:05.619+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-05T14:33:05.620+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.ad_hoc_rnk_amount', extra=None)]
[2025-02-05T14:33:05.621+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T14:33:05.621+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T14:33:05.643+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-05T14:33:05.677+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T14:33:05.720+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.ad_hoc_rnk_amount_run, run_id=manual__2025-02-04T00:00:00+00:00, execution_date=20250204T000000, start_date=20250205T143248, end_date=20250205T143305
[2025-02-05T14:33:05.763+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T14:33:05.791+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T14:33:05.793+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
