[2025-02-04T23:27:24.336+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-04T23:27:24.351+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T23:27:00.226281+00:00 [queued]>
[2025-02-04T23:27:24.359+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T23:27:00.226281+00:00 [queued]>
[2025-02-04T23:27:24.360+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-04T23:27:24.371+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.agg_locations_risk_score_run> on 2025-02-04 23:27:00.226281+00:00
[2025-02-04T23:27:24.377+0000] {standard_task_runner.py:63} INFO - Started process 1150 to run task
[2025-02-04T23:27:24.380+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.agg_locations_risk_score_run', 'manual__2025-02-04T23:27:00.226281+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmpku1yrpy5']
[2025-02-04T23:27:24.381+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask model_credit_fraud.agg_locations_risk_score_run
[2025-02-04T23:27:24.424+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.agg_locations_risk_score_run manual__2025-02-04T23:27:00.226281+00:00 [running]> on host eb20c43aeeb4
[2025-02-04T23:27:24.498+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.agg_locations_risk_score_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T23:27:00.226281+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T23:27:00.226281+00:00'
[2025-02-04T23:27:24.500+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-04T23:27:27.287+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-04T23:27:27.288+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmp8gsgggka from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-04T23:27:27.293+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-04T23:27:27.299+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-04T23:27:27.307+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-04T23:27:27.308+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-04T23:27:27.309+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'agg_locations_risk_score', '--project-dir', '/tmp/tmp8gsgggka', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmp8gsgggka
[2025-02-04T23:27:27.324+0000] {logging_mixin.py:188} INFO - 23:27:27  Running with dbt=1.6.1
[2025-02-04T23:27:27.429+0000] {logging_mixin.py:188} INFO - 23:27:27  Registered adapter: postgres=1.6.1
[2025-02-04T23:27:27.746+0000] {logging_mixin.py:188} INFO - 23:27:27  Found 3 models, 1 snapshot, 5 tests, 1 source, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-04T23:27:27.749+0000] {logging_mixin.py:188} INFO - 23:27:27
[2025-02-04T23:27:27.802+0000] {logging_mixin.py:188} INFO - 23:27:27  Concurrency: 1 threads (target='prod')
[2025-02-04T23:27:27.803+0000] {logging_mixin.py:188} INFO - 23:27:27
[2025-02-04T23:27:27.809+0000] {logging_mixin.py:188} INFO - 23:27:27  1 of 1 START sql table model dm_credit_operations.agg_locations_risk_score ..... [RUN]
[2025-02-04T23:27:31.653+0000] {logging_mixin.py:188} INFO - 23:27:31  1 of 1 OK created sql table model dm_credit_operations.agg_locations_risk_score  [SELECT 5 in 3.84s]
[2025-02-04T23:27:31.666+0000] {logging_mixin.py:188} INFO - 23:27:31
[2025-02-04T23:27:31.667+0000] {logging_mixin.py:188} INFO - 23:27:31  Finished running 1 table model in 0 hours 0 minutes and 3.92 seconds (3.92s).
[2025-02-04T23:27:31.678+0000] {logging_mixin.py:188} INFO - 23:27:31
[2025-02-04T23:27:31.679+0000] {logging_mixin.py:188} INFO - 23:27:31  Completed successfully
[2025-02-04T23:27:31.680+0000] {logging_mixin.py:188} INFO - 23:27:31
[2025-02-04T23:27:31.681+0000] {logging_mixin.py:188} INFO - 23:27:31  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-04T23:27:32.407+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-04T23:27:32.443+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-04T23:27:32.444+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.agg_locations_risk_score', extra=None)]
[2025-02-04T23:27:32.445+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-04T23:27:32.445+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-04T23:27:32.459+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-04T23:27:32.487+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-04T23:27:32.512+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.agg_locations_risk_score_run, run_id=manual__2025-02-04T23:27:00.226281+00:00, execution_date=20250204T232700, start_date=20250204T232724, end_date=20250204T232732
[2025-02-04T23:27:31.948+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-04T23:27:31.962+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-04T23:27:31.965+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
