[2025-02-05T11:53:23.386+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T11:53:23.397+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.dim_vendedor_seed manual__2025-02-05T11:53:16+00:00 [queued]>
[2025-02-05T11:53:23.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.dim_vendedor_seed manual__2025-02-05T11:53:16+00:00 [queued]>
[2025-02-05T11:53:23.404+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T11:53:23.414+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtSeedLocalOperator): model_sales.dim_vendedor_seed> on 2025-02-05 11:53:16+00:00
[2025-02-05T11:53:23.418+0000] {standard_task_runner.py:63} INFO - Started process 1852 to run task
[2025-02-05T11:53:23.421+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_sales', 'model_sales.dim_vendedor_seed', 'manual__2025-02-05T11:53:16+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_sales.py', '--cfg-path', '/tmp/tmpxm87t733']
[2025-02-05T11:53:23.423+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask model_sales.dim_vendedor_seed
[2025-02-05T11:53:23.467+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_sales.model_sales.dim_vendedor_seed manual__2025-02-05T11:53:16+00:00 [running]> on host 98025f4a542d
[2025-02-05T11:53:23.535+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_sales' AIRFLOW_CTX_TASK_ID='model_sales.dim_vendedor_seed' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T11:53:16+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T11:53:16+00:00'
[2025-02-05T11:53:23.538+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T11:53:25.262+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T11:53:25.264+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpwwtb9zoz from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T11:53:25.275+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_sales__model_sales/target/partial_parse.msgpack
[2025-02-05T11:53:25.280+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T11:53:25.287+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T11:53:25.289+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf/profiles.yml.
[2025-02-05T11:53:25.289+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['seed', '--vars', '{"PROD_1": P003,                                 "PROD_2": P002,                                 "DATA_INICIO": 1999-01-01,                                 "DATA_FIM": 2025-02-05}', '--models', 'dim_vendedor', '--project-dir', '/tmp/tmpwwtb9zoz', '--profiles-dir', '/tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf', '--profile', '***', '--target', 'prod']
 in /tmp/tmpwwtb9zoz
[2025-02-05T11:53:25.303+0000] {logging_mixin.py:188} INFO - 11:53:25  Running with dbt=1.6.1
[2025-02-05T11:53:25.391+0000] {logging_mixin.py:188} INFO - 11:53:25  Registered adapter: postgres=1.6.1
[2025-02-05T11:53:25.417+0000] {logging_mixin.py:188} INFO - 11:53:25  Unable to do partial parsing because config vars, config profile, or config target have changed
[2025-02-05T11:53:25.419+0000] {logging_mixin.py:188} INFO - 11:53:25  Unable to do partial parsing because profile has changed
[2025-02-05T11:53:25.420+0000] {logging_mixin.py:188} INFO - 11:53:25  Unable to do partial parsing because env vars used in profiles.yml have changed
[2025-02-05T11:53:26.224+0000] {logging_mixin.py:188} INFO - 11:53:26  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T11:53:26.228+0000] {logging_mixin.py:188} INFO - 11:53:26
[2025-02-05T11:53:26.290+0000] {logging_mixin.py:188} INFO - 11:53:26  Concurrency: 1 threads (target='prod')
[2025-02-05T11:53:26.292+0000] {logging_mixin.py:188} INFO - 11:53:26
[2025-02-05T11:53:26.295+0000] {logging_mixin.py:188} INFO - 11:53:26  1 of 1 START seed file dm_sales.dim_vendedor ................................... [RUN]
[2025-02-05T11:53:26.377+0000] {logging_mixin.py:188} INFO - 11:53:26  1 of 1 OK loaded seed file dm_sales.dim_vendedor ............................... [INSERT 20 in 0.08s]
[2025-02-05T11:53:26.387+0000] {logging_mixin.py:188} INFO - 11:53:26
[2025-02-05T11:53:26.388+0000] {logging_mixin.py:188} INFO - 11:53:26  Finished running 1 seed in 0 hours 0 minutes and 0.16 seconds (0.16s).
[2025-02-05T11:53:26.395+0000] {logging_mixin.py:188} INFO - 11:53:26
[2025-02-05T11:53:26.396+0000] {logging_mixin.py:188} INFO - 11:53:26  Completed successfully
[2025-02-05T11:53:26.397+0000] {logging_mixin.py:188} INFO - 11:53:26
[2025-02-05T11:53:26.397+0000] {logging_mixin.py:188} INFO - 11:53:26  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T11:53:27.420+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T11:53:27.423+0000] {local.py:494} INFO - Inlets: []
[2025-02-05T11:53:27.423+0000] {local.py:495} INFO - Outlets: []
[2025-02-05T11:53:27.424+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T11:53:27.424+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T11:53:27.438+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_sales to None, run_after=None
[2025-02-05T11:53:27.466+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T11:53:27.473+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_sales, task_id=model_sales.dim_vendedor_seed, run_id=manual__2025-02-05T11:53:16+00:00, execution_date=20250205T115316, start_date=20250205T115323, end_date=20250205T115327
[2025-02-05T11:53:27.516+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T11:53:27.534+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T11:53:27.537+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
