[2025-02-05T11:11:21.809+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T11:11:21.834+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.ad_hoc_avg_sales_run manual__2025-02-05T10:26:48.671128+00:00 [queued]>
[2025-02-05T11:11:21.843+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.ad_hoc_avg_sales_run manual__2025-02-05T10:26:48.671128+00:00 [queued]>
[2025-02-05T11:11:21.843+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-02-05T11:11:21.859+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_sales.ad_hoc_avg_sales_run> on 2025-02-05 10:26:48.671128+00:00
[2025-02-05T11:11:21.864+0000] {standard_task_runner.py:63} INFO - Started process 829 to run task
[2025-02-05T11:11:21.868+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_sales', 'model_sales.ad_hoc_avg_sales_run', 'manual__2025-02-05T10:26:48.671128+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_sales.py', '--cfg-path', '/tmp/tmpg5erog67']
[2025-02-05T11:11:21.870+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask model_sales.ad_hoc_avg_sales_run
[2025-02-05T11:11:21.924+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_sales.model_sales.ad_hoc_avg_sales_run manual__2025-02-05T10:26:48.671128+00:00 [running]> on host 98025f4a542d
[2025-02-05T11:11:22.013+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_sales' AIRFLOW_CTX_TASK_ID='model_sales.ad_hoc_avg_sales_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T10:26:48.671128+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T10:26:48.671128+00:00'
[2025-02-05T11:11:22.016+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T11:11:24.491+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T11:11:24.492+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpwfvgasqc from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T11:11:24.504+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_sales__model_sales/target/partial_parse.msgpack
[2025-02-05T11:11:24.511+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T11:11:24.521+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T11:11:24.522+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf/profiles.yml.
[2025-02-05T11:11:24.523+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'ad_hoc_avg_sales', '--project-dir', '/tmp/tmpwfvgasqc', '--profiles-dir', '/tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf', '--profile', '***', '--target', 'prod']
 in /tmp/tmpwfvgasqc
[2025-02-05T11:11:24.539+0000] {logging_mixin.py:188} INFO - 11:11:24  Running with dbt=1.6.1
[2025-02-05T11:11:24.645+0000] {logging_mixin.py:188} INFO - 11:11:24  Registered adapter: postgres=1.6.1
[2025-02-05T11:11:24.669+0000] {logging_mixin.py:188} INFO - 11:11:24  Unable to do partial parsing because profile has changed
[2025-02-05T11:11:24.671+0000] {logging_mixin.py:188} INFO - 11:11:24  Unable to do partial parsing because env vars used in profiles.yml have changed
[2025-02-05T11:11:25.829+0000] {logging_mixin.py:188} INFO - 11:11:25  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T11:11:25.832+0000] {logging_mixin.py:188} INFO - 11:11:25
[2025-02-05T11:11:25.938+0000] {logging_mixin.py:188} INFO - 11:11:25  Concurrency: 1 threads (target='prod')
[2025-02-05T11:11:25.939+0000] {logging_mixin.py:188} INFO - 11:11:25
[2025-02-05T11:11:25.943+0000] {logging_mixin.py:188} INFO - 11:11:25  1 of 1 START sql table model dm_sales.ad_hoc_avg_sales ......................... [RUN]
[2025-02-05T11:11:26.033+0000] {logging_mixin.py:188} INFO - 11:11:26  1 of 1 OK created sql table model dm_sales.ad_hoc_avg_sales .................... [SELECT 10 in 0.09s]
[2025-02-05T11:11:26.044+0000] {logging_mixin.py:188} INFO - 11:11:26
[2025-02-05T11:11:26.045+0000] {logging_mixin.py:188} INFO - 11:11:26  Finished running 1 table model in 0 hours 0 minutes and 0.21 seconds (0.21s).
[2025-02-05T11:11:26.068+0000] {logging_mixin.py:188} INFO - 11:11:26
[2025-02-05T11:11:26.077+0000] {logging_mixin.py:188} INFO - 11:11:26  Completed successfully
[2025-02-05T11:11:26.078+0000] {logging_mixin.py:188} INFO - 11:11:26
[2025-02-05T11:11:26.079+0000] {logging_mixin.py:188} INFO - 11:11:26  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T11:11:27.873+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T11:11:27.951+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_sales.dim_vendedor', extra=None), Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_sales.eventos_vendas', extra=None)]
[2025-02-05T11:11:27.952+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_sales.ad_hoc_avg_sales', extra=None)]
[2025-02-05T11:11:27.952+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T11:11:27.953+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T11:11:27.969+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_sales to None, run_after=None
[2025-02-05T11:11:27.996+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T11:11:28.027+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_sales, task_id=model_sales.ad_hoc_avg_sales_run, run_id=manual__2025-02-05T10:26:48.671128+00:00, execution_date=20250205T102648, start_date=20250205T111121, end_date=20250205T111128
[2025-02-05T11:11:28.076+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T11:11:28.095+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-05T11:11:28.097+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
