[2025-02-05T13:25:49.060+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T13:25:49.078+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.ad_hoc_quantidade_vendas_vendedor_run manual__2025-02-05T13:24:50+00:00 [queued]>
[2025-02-05T13:25:49.088+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_sales.model_sales.ad_hoc_quantidade_vendas_vendedor_run manual__2025-02-05T13:24:50+00:00 [queued]>
[2025-02-05T13:25:49.089+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T13:25:49.104+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_sales.ad_hoc_quantidade_vendas_vendedor_run> on 2025-02-05 13:24:50+00:00
[2025-02-05T13:25:49.111+0000] {standard_task_runner.py:63} INFO - Started process 4025 to run task
[2025-02-05T13:25:49.113+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_sales', 'model_sales.ad_hoc_quantidade_vendas_vendedor_run', 'manual__2025-02-05T13:24:50+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_sales.py', '--cfg-path', '/tmp/tmpgqoqb5e3']
[2025-02-05T13:25:49.115+0000] {standard_task_runner.py:91} INFO - Job 117: Subtask model_sales.ad_hoc_quantidade_vendas_vendedor_run
[2025-02-05T13:25:49.175+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_sales.model_sales.ad_hoc_quantidade_vendas_vendedor_run manual__2025-02-05T13:24:50+00:00 [running]> on host 98025f4a542d
[2025-02-05T13:25:49.280+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_sales' AIRFLOW_CTX_TASK_ID='model_sales.ad_hoc_quantidade_vendas_vendedor_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T13:24:50+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T13:24:50+00:00'
[2025-02-05T13:25:49.283+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T13:25:53.058+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-05T13:25:53.060+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpupdeb2t2 from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-05T13:25:53.069+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_sales__model_sales/target/partial_parse.msgpack
[2025-02-05T13:25:53.076+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-05T13:25:53.089+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-05T13:25:53.090+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf/profiles.yml.
[2025-02-05T13:25:53.091+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--vars', '{"PROD": P003,                                 "LIMITE_QUANTIDADE": 500,                                 "DATA_INICIO": 1999-01-01,                                 "DATA_FIM": 2025-02-05}', '--models', 'ad_hoc_quantidade_vendas_vendedor', '--project-dir', '/tmp/tmpupdeb2t2', '--profiles-dir', '/tmp/cosmos/profile/47873256e3df2d6067f929148b3671caee72f33396318ef25aae33418849eddf', '--profile', '***', '--target', 'prod']
 in /tmp/tmpupdeb2t2
[2025-02-05T13:25:53.115+0000] {logging_mixin.py:188} INFO - 13:25:53  Running with dbt=1.6.1
[2025-02-05T13:25:53.258+0000] {logging_mixin.py:188} INFO - 13:25:53  Registered adapter: postgres=1.6.1
[2025-02-05T13:25:53.995+0000] {logging_mixin.py:188} INFO - 13:25:53  Found 4 models, 1 snapshot, 4 seeds, 5 tests, 3 sources, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-05T13:25:54.000+0000] {logging_mixin.py:188} INFO - 13:25:53
[2025-02-05T13:25:54.099+0000] {logging_mixin.py:188} INFO - 13:25:54  Concurrency: 1 threads (target='prod')
[2025-02-05T13:25:54.101+0000] {logging_mixin.py:188} INFO - 13:25:54
[2025-02-05T13:25:54.107+0000] {logging_mixin.py:188} INFO - 13:25:54  1 of 1 START sql table model dm_sales.ad_hoc_quantidade_vendas_vendedor ........ [RUN]
[2025-02-05T13:25:54.244+0000] {logging_mixin.py:188} INFO - 13:25:54  1 of 1 OK created sql table model dm_sales.ad_hoc_quantidade_vendas_vendedor ... [SELECT 5 in 0.13s]
[2025-02-05T13:25:54.260+0000] {logging_mixin.py:188} INFO - 13:25:54
[2025-02-05T13:25:54.261+0000] {logging_mixin.py:188} INFO - 13:25:54  Finished running 1 table model in 0 hours 0 minutes and 0.26 seconds (0.26s).
[2025-02-05T13:25:54.270+0000] {logging_mixin.py:188} INFO - 13:25:54
[2025-02-05T13:25:54.272+0000] {logging_mixin.py:188} INFO - 13:25:54  Completed successfully
[2025-02-05T13:25:54.274+0000] {logging_mixin.py:188} INFO - 13:25:54
[2025-02-05T13:25:54.276+0000] {logging_mixin.py:188} INFO - 13:25:54  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-05T13:25:55.032+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-05T13:25:55.121+0000] {local.py:494} INFO - Inlets: []
[2025-02-05T13:25:55.128+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_sales.ad_hoc_quantidade_vendas_vendedor', extra=None)]
[2025-02-05T13:25:55.130+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-05T13:25:55.132+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-05T13:25:55.153+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_sales to None, run_after=None
[2025-02-05T13:25:55.191+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T13:25:55.217+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_sales, task_id=model_sales.ad_hoc_quantidade_vendas_vendedor_run, run_id=manual__2025-02-05T13:24:50+00:00, execution_date=20250205T132450, start_date=20250205T132549, end_date=20250205T132555
[2025-02-05T13:25:55.267+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-05T13:25:55.291+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-05T13:25:55.294+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
