[2025-02-04T23:04:15.061+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-04T23:04:15.074+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.ad_hoc_rnk_amount_run manual__2025-02-04T22:52:25.583411+00:00 [queued]>
[2025-02-04T23:04:15.080+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.ad_hoc_rnk_amount_run manual__2025-02-04T22:52:25.583411+00:00 [queued]>
[2025-02-04T23:04:15.081+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-04T23:04:15.090+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.ad_hoc_rnk_amount_run> on 2025-02-04 22:52:25.583411+00:00
[2025-02-04T23:04:15.095+0000] {standard_task_runner.py:63} INFO - Started process 887 to run task
[2025-02-04T23:04:15.098+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.ad_hoc_rnk_amount_run', 'manual__2025-02-04T22:52:25.583411+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmp4k6k9do9']
[2025-02-04T23:04:15.100+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask model_credit_fraud.ad_hoc_rnk_amount_run
[2025-02-04T23:04:15.139+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.ad_hoc_rnk_amount_run manual__2025-02-04T22:52:25.583411+00:00 [running]> on host eb20c43aeeb4
[2025-02-04T23:04:15.198+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.ad_hoc_rnk_amount_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T22:52:25.583411+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T22:52:25.583411+00:00'
[2025-02-04T23:04:15.201+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-04T23:04:17.029+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-04T23:04:17.030+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmpli0vig6l from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-04T23:04:17.037+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-04T23:04:17.043+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-04T23:04:17.054+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-04T23:04:17.089+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-04T23:04:17.091+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'ad_hoc_rnk_amount', '--project-dir', '/tmp/tmpli0vig6l', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmpli0vig6l
[2025-02-04T23:04:17.107+0000] {logging_mixin.py:188} INFO - 23:04:17  Running with dbt=1.6.1
[2025-02-04T23:04:17.187+0000] {logging_mixin.py:188} INFO - 23:04:17  Registered adapter: postgres=1.6.1
[2025-02-04T23:04:17.438+0000] {logging_mixin.py:188} INFO - 23:04:17  Found 3 models, 1 snapshot, 5 tests, 1 source, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-04T23:04:17.440+0000] {logging_mixin.py:188} INFO - 23:04:17
[2025-02-04T23:04:17.497+0000] {logging_mixin.py:188} INFO - 23:04:17  Concurrency: 1 threads (target='prod')
[2025-02-04T23:04:17.498+0000] {logging_mixin.py:188} INFO - 23:04:17
[2025-02-04T23:04:17.501+0000] {logging_mixin.py:188} INFO - 23:04:17  1 of 1 START sql table model dm_credit_operations.ad_hoc_rnk_amount ............ [RUN]
[2025-02-04T23:04:25.680+0000] {logging_mixin.py:188} INFO - 23:04:25  1 of 1 OK created sql table model dm_credit_operations.ad_hoc_rnk_amount ....... [SELECT 3 in 8.18s]
[2025-02-04T23:04:25.690+0000] {logging_mixin.py:188} INFO - 23:04:25
[2025-02-04T23:04:25.690+0000] {logging_mixin.py:188} INFO - 23:04:25  Finished running 1 table model in 0 hours 0 minutes and 8.25 seconds (8.25s).
[2025-02-04T23:04:25.697+0000] {logging_mixin.py:188} INFO - 23:04:25
[2025-02-04T23:04:25.698+0000] {logging_mixin.py:188} INFO - 23:04:25  Completed successfully
[2025-02-04T23:04:25.700+0000] {logging_mixin.py:188} INFO - 23:04:25
[2025-02-04T23:04:25.701+0000] {logging_mixin.py:188} INFO - 23:04:25  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-04T23:04:26.737+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-04T23:04:26.763+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-04T23:04:26.764+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.ad_hoc_rnk_amount', extra=None)]
[2025-02-04T23:04:26.765+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-04T23:04:26.767+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-04T23:04:26.779+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-04T23:04:26.800+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-04T23:04:26.822+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.ad_hoc_rnk_amount_run, run_id=manual__2025-02-04T22:52:25.583411+00:00, execution_date=20250204T225225, start_date=20250204T230415, end_date=20250204T230426
[2025-02-04T23:04:26.851+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-04T23:04:26.863+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-04T23:04:26.865+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
