[2025-02-04T23:27:09.744+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-04T23:27:09.754+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.ad_hoc_rnk_amount_run manual__2025-02-04T23:27:00.226281+00:00 [queued]>
[2025-02-04T23:27:09.760+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.ad_hoc_rnk_amount_run manual__2025-02-04T23:27:00.226281+00:00 [queued]>
[2025-02-04T23:27:09.761+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-04T23:27:09.770+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): model_credit_fraud.ad_hoc_rnk_amount_run> on 2025-02-04 23:27:00.226281+00:00
[2025-02-04T23:27:09.774+0000] {standard_task_runner.py:63} INFO - Started process 1129 to run task
[2025-02-04T23:27:09.776+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt-model_credit_fraud', 'model_credit_fraud.ad_hoc_rnk_amount_run', 'manual__2025-02-04T23:27:00.226281+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_dbt-model_fraud_credit.py', '--cfg-path', '/tmp/tmplg8j72vw']
[2025-02-04T23:27:09.778+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask model_credit_fraud.ad_hoc_rnk_amount_run
[2025-02-04T23:27:09.813+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_dbt-model_credit_fraud.model_credit_fraud.ad_hoc_rnk_amount_run manual__2025-02-04T23:27:00.226281+00:00 [running]> on host eb20c43aeeb4
[2025-02-04T23:27:09.870+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_dbt-model_credit_fraud' AIRFLOW_CTX_TASK_ID='model_credit_fraud.ad_hoc_rnk_amount_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T23:27:00.226281+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T23:27:00.226281+00:00'
[2025-02-04T23:27:09.872+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-04T23:27:11.475+0000] {local.py:220} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-02-04T23:27:11.476+0000] {local.py:436} INFO - Cloning project to writable temp directory /tmp/tmp1c7s833_ from /usr/local/airflow/dags/dbt/localiza_dw
[2025-02-04T23:27:11.480+0000] {local.py:447} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dag_dbt-model_credit_fraud__model_credit_fraud/target/partial_parse.msgpack
[2025-02-04T23:27:11.484+0000] {config.py:348} INFO - Profile caching is enable.
[2025-02-04T23:27:11.491+0000] {base.py:84} INFO - Using connection ID '***' for task execution.
[2025-02-04T23:27:11.492+0000] {config.py:328} INFO - Profile found in cache using profile: /tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211/profiles.yml.
[2025-02-04T23:27:11.493+0000] {local.py:408} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'ad_hoc_rnk_amount', '--project-dir', '/tmp/tmp1c7s833_', '--profiles-dir', '/tmp/cosmos/profile/bdc35343eb23031ee554202b16407e794194afcc614f7ea62bc658c63495a211', '--profile', '***', '--target', 'prod']
 in /tmp/tmp1c7s833_
[2025-02-04T23:27:11.504+0000] {logging_mixin.py:188} INFO - 23:27:11  Running with dbt=1.6.1
[2025-02-04T23:27:11.581+0000] {logging_mixin.py:188} INFO - 23:27:11  Registered adapter: postgres=1.6.1
[2025-02-04T23:27:11.818+0000] {logging_mixin.py:188} INFO - 23:27:11  Found 3 models, 1 snapshot, 5 tests, 1 source, 0 exposures, 0 metrics, 349 macros, 0 groups, 0 semantic models
[2025-02-04T23:27:11.820+0000] {logging_mixin.py:188} INFO - 23:27:11
[2025-02-04T23:27:11.867+0000] {logging_mixin.py:188} INFO - 23:27:11  Concurrency: 1 threads (target='prod')
[2025-02-04T23:27:11.868+0000] {logging_mixin.py:188} INFO - 23:27:11
[2025-02-04T23:27:11.872+0000] {logging_mixin.py:188} INFO - 23:27:11  1 of 1 START sql table model dm_credit_operations.ad_hoc_rnk_amount ............ [RUN]
[2025-02-04T23:27:19.890+0000] {logging_mixin.py:188} INFO - 23:27:19  1 of 1 OK created sql table model dm_credit_operations.ad_hoc_rnk_amount ....... [SELECT 3 in 8.02s]
[2025-02-04T23:27:19.900+0000] {logging_mixin.py:188} INFO - 23:27:19
[2025-02-04T23:27:19.901+0000] {logging_mixin.py:188} INFO - 23:27:19  Finished running 1 table model in 0 hours 0 minutes and 8.08 seconds (8.08s).
[2025-02-04T23:27:19.909+0000] {logging_mixin.py:188} INFO - 23:27:19
[2025-02-04T23:27:19.910+0000] {logging_mixin.py:188} INFO - 23:27:19  Completed successfully
[2025-02-04T23:27:19.911+0000] {logging_mixin.py:188} INFO - 23:27:19
[2025-02-04T23:27:19.912+0000] {logging_mixin.py:188} INFO - 23:27:19  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-04T23:27:20.649+0000] {local.py:138} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v10.json is above dbt-ol supported version 7. This might cause errors.
[2025-02-04T23:27:20.685+0000] {local.py:494} INFO - Inlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.stg_credit_fraud', extra=None)]
[2025-02-04T23:27:20.686+0000] {local.py:495} INFO - Outlets: [Dataset(uri='postgres://postgres-db:5432/localiza_dw.dm_credit_operations.ad_hoc_rnk_amount', extra=None)]
[2025-02-04T23:27:20.687+0000] {local.py:595} INFO - Assigning inlets/outlets without DatasetAlias
[2025-02-04T23:27:20.688+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-04T23:27:20.701+0000] {dag.py:3954} INFO - Setting next_dagrun for dag_dbt-model_credit_fraud to None, run_after=None
[2025-02-04T23:27:20.729+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-04T23:27:20.752+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_dbt-model_credit_fraud, task_id=model_credit_fraud.ad_hoc_rnk_amount_run, run_id=manual__2025-02-04T23:27:00.226281+00:00, execution_date=20250204T232700, start_date=20250204T232709, end_date=20250204T232720
[2025-02-04T23:27:20.791+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-02-04T23:27:20.804+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-04T23:27:20.807+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
